/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JZypp */

#ifndef _Included_JZypp
#define _Included_JZypp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JZypp
 * Method:    whatProvides
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JZypp_whatProvides
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
