/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_univsavoie_serveurbeta_trap_JZypp */

#ifndef _Included_fr_univsavoie_serveurbeta_trap_JZypp
#define _Included_fr_univsavoie_serveurbeta_trap_JZypp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_univsavoie_serveurbeta_trap_JZypp
 * Method:    isAValidRepository
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univsavoie_serveurbeta_trap_JZypp_isAValidRepository
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fr_univsavoie_serveurbeta_trap_JZypp
 * Method:    SearchPackage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_univsavoie_serveurbeta_trap_JZypp_searchPackage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
