/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_univsavoie_serveurbeta_trap_JZypp */

#ifndef _Included_fr_univsavoie_serveurbeta_trap_JZypp
#define _Included_fr_univsavoie_serveurbeta_trap_JZypp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_univsavoie_serveurbeta_trap_JZypp
 * Method:    isAValidRepository
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_univsavoie_serveurbeta_trap_JZypp_isAValidRepository
  (JNIEnv *, jobject, jstring);

/*
 * Class:     fr_univsavoie_serveurbeta_trap_JZypp
 * Method:    getPackage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_univsavoie_serveurbeta_trap_JZypp_getPackage
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fr_univsavoie_serveurbeta_trap_JZypp
 * Method:    addRepository
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_univsavoie_serveurbeta_trap_JZypp_addRepository__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     fr_univsavoie_serveurbeta_trap_JZypp
 * Method:    addRepository
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_univsavoie_serveurbeta_trap_JZypp_addRepository__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     fr_univsavoie_serveurbeta_trap_JZypp
 * Method:    getPackagesFromName
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_univsavoie_serveurbeta_trap_JZypp_getPackagesFromName
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     fr_univsavoie_serveurbeta_trap_JZypp
 * Method:    getPackagesFromRepo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_univsavoie_serveurbeta_trap_JZypp_getPackagesFromRepo
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fr_univsavoie_serveurbeta_trap_JZypp
 * Method:    refreshRepo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_univsavoie_serveurbeta_trap_JZypp_refreshRepo
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fr_univsavoie_serveurbeta_trap_JZypp
 * Method:    setPathName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_univsavoie_serveurbeta_trap_JZypp_setPathName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
